---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ollama-proxy-token
  namespace: ai-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-otter
    kind: ClusterSecretStore
  target:
    name: ollama-proxy-token
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /ollama-proxy/token
        property: token
      secretKey: token
