---
roles: []

collections:
  - name: community.general
    version: 13.3.0
  - name: k3s.orchestration
    type: git
    version: 1.2.2
    source: https://github.com/k3s-io/k3s-ansible.git
  - name: ansible.utils
    version: 6.1.0
  - name: kubernetes.core
    version: 6.5.0
