---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-otter
spec:
  provider:
    vault:
      server: "https://vault.derwitt.site"
      path: "otter"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-otter-path-token"
          namespace: external-secrets
          key: "token"
