---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [originAnnotations]
# The namespace is owned by the node-exporter component, which shares it.
resources:
  - helm-repository.fluxcd.yaml
  - helm-release.fluxcd.yaml
