---
# Written by the k3s role for the ansible user (user_kubectl), and read by both the flux CLI and
# kubernetes.core via KUBECONFIG.
kubeconfig_path: "{{ ansible_facts['env']['HOME'] }}/.kube/localhost/config"
