---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [originAnnotations]
resources:
  - external-secrets.yaml
  - external-secrets-stores.yaml
  - infrastructure.yaml
  - mogenius-platform-config-dev.yaml
  - apps.yaml
