---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitops-write-token
  namespace: mogenius-operator-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-otter
    kind: ClusterSecretStore
  target:
    name: gitops-write-token
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /mogenius-operator-dev/gitops
        property: jotunheim-write-token
      secretKey: jotunheim-write-token
